[package]
name = "buf_file"
version = "0.1.0"
authors = ["Josh Karns <jkarns275@gmail.com>"]
description = "A Buffered File that allows for both reading and writing"
license = "MIT"

[dependencies]
raw_serde = "0.1.4"
